name: techpointchallenge
description: Submission to Techpoint's S.O.S. challenge 2020

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  auto_size_text: ^2.1.0
  cached_network_image: ^2.2.0+1
  cloud_firestore: ^0.13.7
  cupertino_icons: ^0.1.3
  duration: ^2.0.14
  firebase: ^7.3.0
  firebase_auth: ^0.16.1
  firebase_core: ^0.4.5
  flutter:
    sdk: flutter
  flutter_signin_button: ^1.0.0
  google_fonts: ^1.1.0
  google_sign_in: ^4.1.0
  intl: ^0.16.1
  material_design_icons_flutter: 4.0.5345
  provider: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

